In [90]:
import pandas as pd
import os
import seaborn as sns
import matplotlib.pyplot as plt
# from sklearn.model_selection import train_test_split
# from sklearn.linear_model import LogisticRegression
# from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

base_path = "D:/manualCDmanagement/codes/Projects/VMs/skl algorithms/Logistic Regression/diabetes.v1/Storage"
file_name = "heart_disease_dataset.csv"
file_path = os.path.join(base_path, file_name)

df = pd.read_csv(file_path) 

print(df.head())

   Age  Gender  Cholesterol  Blood Pressure  Heart Rate  Smoking  \
0   75  Female          228             119          66  Current
1   48    Male          204             165          62  Current
2   53    Male          234              91          67    Never
3   69  Female          192              90          72  Current
4   62  Female          172             163          93    Never

  Alcohol Intake  Exercise Hours Family History Diabetes Obesity  \
0          Heavy               1             No       No     Yes
1            NaN               5             No       No      No
2          Heavy               3            Yes       No     Yes
3            NaN               4             No      Yes      No
4            NaN               6             No      Yes      No

   Stress Level  Blood Sugar Exercise Induced Angina   Chest Pain Type  \
0             8          119                     Yes   Atypical Angina
1             9           70                     Yes    Typical Angina
2             5          196                     Yes   Atypical Angina
3             7          107                     Yes  Non-anginal Pain
4             2          183                     Yes      Asymptomatic

   Heart Disease
0              1
1              0
2              1
3              0
4              0

In [91]:

# # Exploratory Data Analysis (EDA)
# Check for missing values
# print(df.isnull().sum())

# # Summary statistics
# print(df.describe())

df['Gender'] = df['Gender'].map({'Male': 0, 'Female': 1})
df['Smoking'] = df['Smoking'].map({'Current': 2, 'Never': 0, "Former": 1})
df['Family History'] = df['Family History'].map({'Yes': 1, 'No': 0})
df['Diabetes'] = df['Diabetes'].map({'Yes': 1, 'No': 0})
df['Obesity'] = df['Obesity'].map({'Yes': 1, 'No': 0})
df['Exercise Induced Angina'] = df['Exercise Induced Angina'].map({'Yes': 1, 'No': 0})
df['Chest Pain Type'] = df['Chest Pain Type'].map({'Typical Angina': 3, 'Atypical Angina': 2, 'Non-anginal Pain': 1, 'Asymptomatic': 0})
df['Alcohol Intake'] = df['Alcohol Intake'].fillna('None').map({'Heavy': 2, 'Moderate': 1, 'None':1})

['Heavy' nan 'Moderate']

In [93]:


# # Correlation matrix
# corr_matrix = df.corr()
# plt.figure(figsize=(12, 8))
# sns.heatmap(corr_matrix, annot=True, cmap='coolwarm')
# plt.title('Correlation Matrix')

## Save image
# fig_name = "Correlation matrix.png"
# bp = base_path + "/Figures"
# save_to = os.path.join(bp, fig_name)
# # plt.savefig(save_to)
# plt.savefig(save_to, dpi=300, bbox_inches='tight')

# # plt.show()

df.head(10)


# df.head()

# # Pairplot
# sns.pairplot(df, hue='Smoking')
# plt.show()

# # Split the data into features and target
# X = df.drop('target', axis=1)  # 'target' is the target variable in the dataset
# y = df['target']

# # Split the dataset into training and testing sets
# X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# # Initialize and train the logistic regression model
# model = LogisticRegression(max_iter=1000)
# model.fit(X_train, y_train)

# # Make predictions on the test set
# y_pred = model.predict(X_test)

# # Evaluate the model
# accuracy = accuracy_score(y_test, y_pred)
# conf_matrix = confusion_matrix(y_test, y_pred)
# class_report = classification_report(y_test, y_pred)

# print(f"Accuracy: {accuracy}")
# print("Confusion Matrix:")
# print(conf_matrix)
# print("Classification Report:")
# print(class_report)

,Age,Gender,Cholesterol,Blood Pressure,Heart Rate,Smoking,Alcohol Intake,Exercise Hours,Family History,Diabetes,Obesity,Stress Level,Blood Sugar,Exercise Induced Angina,Chest Pain Type,Heart Disease
0,75,1,228,119,66,2,2,1,0,0,1,8,119,1,2,1
1,48,0,204,165,62,2,1,5,0,0,0,9,70,1,3,0
2,53,0,234,91,67,0,2,3,1,0,1,5,196,1,2,1
3,69,1,192,90,72,2,1,4,0,1,0,7,107,1,1,0
4,62,1,172,163,93,0,1,6,0,1,0,2,183,1,0,0
5,77,0,309,110,73,0,1,0,0,1,1,4,122,1,0,1
6,64,1,211,105,86,1,2,8,1,1,1,2,120,0,3,1
7,60,1,208,148,83,0,1,4,0,1,1,2,113,1,0,1
8,37,1,317,137,66,2,2,3,0,1,1,5,114,0,1,0
9,63,0,204,141,68,1,2,8,0,1,0,3,107,0,0,1